#!/usr/libexec/atf-sh

#
# Verify that the example tasks work.
#

. $(atf_get_srcdir)/_env.sh

atf_test_case hello_world
hello_world_body()
{
	atf_check -o inline:"Hello, world!\n" \
	    bricoler runtask example/hello-world
	atf_check -o inline:"Hello, markj!\n" \
	    bricoler runtask -p addressee=markj example/hello-world
	atf_check -o empty -e match:"Binding non-existent parameter 'addresseee'" \
	    -s not-exit:0 \
	    bricoler runtask -p addresseee=markj example/hello-world
}

atf_test_case hello_input
hello_input_body()
{
	atf_check -o inline:"Hello, markj!\nGoodbye!\n" \
	    bricoler runtask example/hello-input
	atf_check -o inline:"Hello, jkram!\nGoodbye!\n" \
	    bricoler runtask -p hello:addressee=jkram example/hello-input
}

atf_test_case hello_output
hello_output_body()
{
	atf_check -o empty \
	    bricoler runtask example/hello-output
	atf_check -o inline:"hello\n" \
	    bricoler runtask example/hello-output-parent
	atf_check -o inline:"goodbye\n" \
	    bricoler runtask -p output:msg=goodbye example/hello-output-parent
}

atf_test_case hello_multi_input
hello_multi_input_body()
{
        # Don't assume that dependencies are run in any particular order.
	atf_check \
	    -o match:"^Hello, markj!$" \
	    -o match:"^Hello, jkram!$" \
	    bricoler runtask example/hello-multi-input
	atf_check \
	    -o match:"^Hello, tuft!$" \
	    -o match:"^Hello, scrum!$" \
	    bricoler runtask \
	        -p first_hello:addressee=tuft \
		-p second_hello:addressee=scrum \
		example/hello-multi-input
}

atf_test_case hello_valid
hello_valid_body()
{
	atf_check -o inline:"This is the only valid message.\n" \
	    bricoler runtask -p msg1="This is the only valid message." example/hello-valid
	atf_check -o empty -s not-exit:0 \
	    -e match:"Validation of parameter 'msg1' value 'plibt' failed" \
	    bricoler runtask -p msg1="plibt" example/hello-valid
	atf_check -o inline:"This is the only valid message.\nhello\n" \
	    bricoler runtask -p msg1="This is the only valid message." -p msg2="hello" \
	    example/hello-valid
	atf_check -o empty -s not-exit:0 \
	    -e match:"Validation of parameter 'msg2' value 'plibt' failed" \
	    bricoler runtask -p msg1="This is the only valid message." -p msg2=plibt \
	    example/hello-valid
}

atf_init_test_cases()
{
	atf_add_test_case hello_world
	atf_add_test_case hello_input
	atf_add_test_case hello_output
	atf_add_test_case hello_multi_input
	atf_add_test_case hello_valid
}
